version: '3'
services:
  nginx:
    image: nginx:latest 
    container_name: nginx-container  
    ports:  
    - 80:80

  mysql:    
    image: mysql:5.7  
    container_name: mysql-container 
    environment:  
     MYSQL_ROOT_PASSWORD: secret  
     MYSQL_DATABASE: mydb  
     MYSQL_USER: myuser  
     MYSQL_PASSWORD: password